apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: 	arn:aws:iam::389285903811:role/eks-kubernetes-worker-nodes-NodeInstanceRole-S3OZAME8G0C4
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
